nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  pendle:
    npmAlwaysAuth: true
    npmAuthToken: "${PENDLE_SDK_V2_NPM_AUTH_TOKEN:-Please set your access token}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"
