# prevent yarn v2+ to use pnp
nodeLinker: node-modules

npmScopes:
  pendle:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"
    npmAlwaysAuth: true
    npmAuthToken: ${PENDLE_SDK_V2_NPM_AUTH_TOKEN:-Please set your access token}

npmPublishAccess: public
