import { MAINNET_CONTRACT_ADDRESSES } from './mainnet';
import { FUJI_TESTNET_CONTRACT_ADDRESSES } from './testnet';
import { MUMBAI_TESTNET_CONTRACT_ADDRESSES } from './mumbai';

import { CHAIN_ID_MAPPING } from '../../../src';

export const CONTRACT_ADDRESSES = {
    [CHAIN_ID_MAPPING.FUJI]: FUJI_TESTNET_CONTRACT_ADDRESSES,
    [CHAIN_ID_MAPPING.ETHEREUM]: MAINNET_CONTRACT_ADDRESSES,
    [CHAIN_ID_MAPPING.MUMBAI]: MUMBAI_TESTNET_CONTRACT_ADDRESSES,
};

// choose the markets you want to test here
export const MARKET_TO_TEST = {
    [CHAIN_ID_MAPPING.FUJI]: CONTRACT_ADDRESSES[CHAIN_ID_MAPPING.FUJI].MARKETS_BY_NAME.FUJI_QIUSDC_FEB02_ADDRESSES,
    [CHAIN_ID_MAPPING.ETHEREUM]:
        CONTRACT_ADDRESSES[CHAIN_ID_MAPPING.ETHEREUM].MARKETS_BY_NAME.MAINNET_FRAX_MAR23_ADDRESSES,
    [CHAIN_ID_MAPPING.MUMBAI]:
        CONTRACT_ADDRESSES[CHAIN_ID_MAPPING.MUMBAI].MARKETS_BY_NAME.MUMBAI_QIUSDC_FEB04_ADDRESSES,
} as const;
