import { MAINNET_CONTRACT_ADDRESSES } from './mainnet';
import { FUJI_TESTNET_CONTRACT_ADDRESSES } from './testnet';
import { MUMBAI_TESTNET_CONTRACT_ADDRESSES } from './mumbai';

import { CHAIN_ID_MAPPING } from '../../../src';
import { ARBITRUM_CONTRACT_ADDRESSES } from './arbitrum';

export const CONTRACT_ADDRESSES = {
    [CHAIN_ID_MAPPING.FUJI]: FUJI_TESTNET_CONTRACT_ADDRESSES,
    [CHAIN_ID_MAPPING.ETHEREUM]: MAINNET_CONTRACT_ADDRESSES,
    [CHAIN_ID_MAPPING.MUMBAI]: MUMBAI_TESTNET_CONTRACT_ADDRESSES,
    [CHAIN_ID_MAPPING.ARBITRUM]: ARBITRUM_CONTRACT_ADDRESSES,
};

// choose the markets you want to test here
export const MARKET_TO_TEST = {
    [CHAIN_ID_MAPPING.FUJI]: CONTRACT_ADDRESSES[CHAIN_ID_MAPPING.FUJI].MARKETS_BY_NAME.APE_MARCH30_ADDRESSES,
    [CHAIN_ID_MAPPING.ETHEREUM]:
        CONTRACT_ADDRESSES[CHAIN_ID_MAPPING.ETHEREUM].MARKETS_BY_NAME.MAINNET_SFRXETH_26DEC2024_ADDRESSES,
    [CHAIN_ID_MAPPING.MUMBAI]:
        CONTRACT_ADDRESSES[CHAIN_ID_MAPPING.MUMBAI].MARKETS_BY_NAME.MUMBAI_QIUSDC_DEC08_ADDRESSES,
    [CHAIN_ID_MAPPING.ARBITRUM]:
        CONTRACT_ADDRESSES[CHAIN_ID_MAPPING.ARBITRUM].MARKETS_BY_NAME.ARBITRUM_GLP_MAR28_2024_ADDRESSES,
} as const;
