name: Setup node and yarn environment
description: Setup node and yarn environment

inputs:
    NPM_TOKEN:
        description: NPM token to pass to scope
        required: true

runs:
    using: 'composite'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'yarn'
        
    - name: Set authentication token
      run: 'yarn config set npmScopes.pendle.npmAuthToken "${NPM_AUTH_TOKEN}"'
      env:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
      shell: bash
        
    - name: Run install
      run: yarn install --immutable
      shell: bash
