name: ci
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
    - name: Lint with eslint
      run: yarn eslint "{src,test}/**/*.{ts,js}"
