name: Lint and typecheck
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      uses: ./.github/workflows/setup-env.yml

    - name: Lint 
      run: yarn lint:nofix
        
    - name: Type checking
      run: yarn typecheck


